// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Inspect or stage server availability for the next complete turn in a live thread.
 */
export type McpServerSelectionParams = { threadId: string,
/**
 * Omit to inspect without side effects. An empty list deselects optional servers.
 */
selectedServers?: Array<string> | null, };
