// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { McpServerConnectionStatus } from "./McpServerConnectionStatus";

export type McpServerSelectionEntry = { name: string, selected: boolean, lockedReason: string | null, connectionStatus: McpServerConnectionStatus, };
